Repository shap/shap, pull requests merged in 2023-12, with the labels that each got.

#3386 ENH: Add support for Explanation.display_data in bar plot
  shap/plots/_bar.py
Labels: enhancement, visualization

#3405 Add Contributing guide to published Sphinx docs
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  pyproject.toml
Labels: documentation

#3407 MAINT: Configure Ruff formatter, update ruff config
  .pre-commit-config.yaml
  notebooks/benchmarks/tabular/Benchmark XGBoost explanations.ipynb
  notebooks/tabular_examples/linear_models/Explaining a model that uses standardized features.ipynb
  notebooks/tabular_examples/linear_models/Sentiment Analysis with Logistic Regression.ipynb
  notebooks/tabular_examples/tree_based_models/Python Version of Tree SHAP.ipynb
  pyproject.toml
Labels: skip-changelog

#3410 Fix ambiguous variable names
  pyproject.toml
  shap/_explanation.py
  shap/benchmark/_explanation_error.py
  shap/benchmark/_sequential.py
  shap/benchmark/plots.py
  shap/explainers/_deep/deep_pytorch.py
  shap/explainers/_deep/deep_tf.py
  shap/explainers/_deep/deep_utils.py
  shap/explainers/_gradient.py
  shap/explainers/_tree.py
  shap/plots/_bar.py
  shap/plots/_waterfall.py
  shap/plots/colors/_colors.py
  shap/utils/_keras.py
  shap/utils/_legacy.py
  tests/explainers/test_tree.py
Labels: skip-changelog

#3404 Add maintainer guide to docs to explain versioning and releasing
  CONTRIBUTING.md
Labels: documentation

#3402 MAINT: Add version number from git tag using setuptools scm
  .github/workflows/build_wheels.yml
  .gitignore
  MANIFEST.in
  pyproject.toml
  shap/__init__.py
Labels: ci, skip-changelog

#3424 MAINT: Enable stale bot in debug mode
  .github/workflows/stale_issues.yml
  CONTRIBUTING.md
Labels: ci, skip-changelog

#3427 Stale bot: process oldest issues first
  .github/workflows/stale_issues.yml
Labels: skip-changelog
