Repository shap/shap, pull requests merged in 2023-08, with the labels that each got.

#3175 DOCS: Fix failing ReadTheDocs build, pin Sphinx dependencies
  pyproject.toml
Labels: bug, documentation

#3141 MAINT: Improve Contributing Guide
  .github/ISSUE_TEMPLATE/bug-report.yml
  CONTRIBUTING.md
Labels: documentation

#3155 MAINT: fixup overly permissive regex pattern
  shap/maskers/_text.py
Labels: good first issue

#3183 DOCS: Fixup sidebar, add captions and restore logo
  docs/Makefile
  docs/api_examples.rst
  docs/index.rst
  pyproject.toml
Labels: documentation

#3180 MAINT: Remove deprecated system_packages from RtD
  .readthedocs.yml
Labels: documentation, good first issue

#3148 JS: Rebuild bundle.js using updated dependencies
  shap/plots/resources/bundle.js
Labels: dependencies, javascript

#3126 fix: slice `feature_names` properly in Explanation objects with square `.values`
  shap/_explanation.py
  tests/test_explanation.py
Labels: bug

#3196 docs: Fix the truncated autosummary of SamplingExplainer
  notebooks/Untitled.ipynb
  shap/explainers/_sampling.py
Labels: documentation

#3218 docs: clarify behaviour change in the `sample` function
  shap/utils/_general.py
Labels: documentation

#3111 DOCS: Enable pre-commit checks for notebooks
  .pre-commit-config.yaml
  notebooks/api_examples/explainers/Exact.ipynb
  notebooks/api_examples/explainers/GPUTree.ipynb
  notebooks/api_examples/explainers/Permutation.ipynb
  notebooks/api_examples/maskers/custom.ipynb
  notebooks/api_examples/plots/text.ipynb
  notebooks/genomic_examples/DeepExplainer Genomics Example.ipynb
  notebooks/image_examples/image_classification/Image Multi Class.ipynb
  notebooks/tabular_examples/tree_based_models/Python Version of Tree SHAP.ipynb
  pyproject.toml
Labels: ci, documentation
