Repository shap/shap, pull requests merged in 2023-09, with the labels that each got.

#3121 fix!: Standardize the shape of `Explanation.base_values` of TreeExplainers
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug, BREAKING

#3230 DOCS: Lint & format all API examples notebooks
  .pre-commit-config.yaml
  notebooks/api_examples/explainers/GPUTree.ipynb
  notebooks/api_examples/explainers/Permutation.ipynb
  notebooks/api_examples/plots/bar.ipynb
  notebooks/api_examples/plots/beeswarm.ipynb
  notebooks/api_examples/plots/decision_plot.ipynb
  notebooks/api_examples/plots/heatmap.ipynb
  notebooks/api_examples/plots/image.ipynb
  notebooks/api_examples/plots/scatter.ipynb
  notebooks/api_examples/plots/text.ipynb
  notebooks/api_examples/plots/violin.ipynb
  notebooks/api_examples/plots/waterfall.ipynb
Labels: documentation

#3233 DOCS: Lint & format benchmarks
  .pre-commit-config.yaml
  notebooks/benchmarks/image/Image Multiclass Classification Benchmark Demo.ipynb
  notebooks/benchmarks/others/Benchmark Debug Mode.ipynb
  notebooks/benchmarks/tabular/Benchmark XGBoost explanations.ipynb
  notebooks/benchmarks/tabular/Tabular Prediction Benchmark Demo.ipynb
  notebooks/benchmarks/text/Abstractive Summarization Benchmark Demo.ipynb
  notebooks/benchmarks/text/Machine Translation Benchmark Demo.ipynb
  notebooks/benchmarks/text/Text Emotion Multiclass Classification Benchmark Demo.ipynb
  notebooks/genomic_examples/DeepExplainer Genomics Example.ipynb
Labels: documentation

#3255 MAINT: Fix failing tests, pin XGBoost in test dependencies to 1.7.6
  pyproject.toml
Labels: dependencies, ci

#3265 Enh/3263: PyTorchDeep now also allows to check for additivity (activated by default)
  shap/explainers/_deep/__init__.py
  shap/explainers/_deep/deep_pytorch.py
  shap/explainers/_deep/deep_tf.py
  shap/explainers/_deep/deep_utils.py
Labels: enhancement

#3286 MAINT: Revert transformer model in tests to previous larger model
  tests/explainers/conftest.py
Labels: bug, dependencies
