Repository shap/shap, pull requests merged in 2023-07, with the labels that each got.

#3033 FIX: update code coverage configuration for installed package
  .github/workflows/run_tests.yml
  pyproject.toml
  tests/test_install.py
Labels: bug, ci

#3054 CHORE: changelog updates
  CHANGELOG.md
Labels: documentation

#3048 CHORE: Explicit random seed for tests
  CHANGELOG.md
  tests/benchmark/perturbation.py
  tests/conftest.py
  tests/explainers/test_deep.py
  tests/explainers/test_gradient.py
  tests/explainers/test_kernel.py
  tests/explainers/test_linear.py
  tests/explainers/test_permutation.py
  tests/explainers/test_tree.py
  tests/plots/conftest.py
  tests/plots/test_decision.py
  tests/plots/test_violin.py
  tests/test_explanation.py
Labels: enhancement, ci

#3058 Bump version
  shap/__init__.py
Labels: dependencies

#3078 Build macos arm64 wheels
  pyproject.toml
Labels: ci

#2697 Fix shap.summary_plot to work with matplotlib 3.6.0
  shap/plots/_beeswarm.py
  shap/plots/_violin.py
Labels: bug

#3083 Build wheels in parallel, add aarch64
  .github/workflows/build_wheels.yml
  CHANGELOG.md
  pyproject.toml
  shap/__init__.py
Labels: dependencies, ci

#3080 MAINT: Add codecov.yml, specify `after_n_builds`
  .github/codecov.yml
  .github/workflows/run_tests.yml
Labels: ci

#3085 DOCS: Add version badges
  README.md
Labels: enhancement

#3093 fix: segmentation faults on MacOS with lightgbm tests (with newer libomp versions)
  CHANGELOG.md
  tests/conftest.py
Labels: bug, ci

#3084 FIX: address 3rd party deprecation warnings: numba, xgboost, typing, distutils
  pyproject.toml
  shap/explainers/_deep/deep_tf.py
  shap/maskers/_image.py
  shap/utils/_legacy.py
  tests/explainers/test_tree.py
  tests/maskers/test_text.py
Labels: ci

#3062 API: Multi-output summary plot legend
  CHANGELOG.md
  shap/plots/_beeswarm.py
  tests/plots/baseline/test_random_multi_class_summary_legend.png
  tests/plots/baseline/test_random_multi_class_summary_legend_decimals.png
  tests/plots/test_summary.py
Labels: enhancement

#3094 fix: support LightGBM ensemble containing single leaf trees (stump)
  CHANGELOG.md
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug

#3079 MAINT: Drop python 3.7
  .github/workflows/run_tests.yml
  CHANGELOG.md
  pyproject.toml
Labels: dependencies

#2974 ENH: Update JS lockfile, add CI job to build JS package
  .github/workflows/test_js.yml
  javascript/babel.config.js
  javascript/jest.config.js
  javascript/package-lock.json
  javascript/package.json
  javascript/test_bundle.js
  javascript/tests/__snapshots__/render.spec.jsx.snap
  javascript/tests/render.spec.jsx
  javascript/webpack.config.js
Labels: help wanted, dependencies, javascript

#3108 Add explicit dependabot config
  .github/dependabot.yml
Labels: dependencies, javascript

#3096 fix: pytest imports for isolation forests
  tests/explainers/test_tree.py
Labels: ci

#3091 ENH: Explicitly define public API in modules
  pyproject.toml
  shap/__init__.py
  shap/actions/__init__.py
  shap/benchmark/__init__.py
  shap/explainers/__init__.py
  shap/explainers/other/__init__.py
  shap/maskers/__init__.py
  shap/models/__init__.py
  shap/plots/__init__.py
  shap/plots/colors/__init__.py
  shap/utils/__init__.py
Labels: enhancement

#3112 Update notebook Explaining a model that uses standardized features
  notebooks/tabular_examples/linear_models/Explaining a model that uses standardized features.ipynb
Labels: documentation

#3107 MAINT: Enable CI test skipping by path filter
  .github/workflows/run_tests.yml
Labels: ci

#3118 chore: start testing ngboost and gpboost
  pyproject.toml
  tests/explainers/test_tree.py
Labels: dependencies, ci

#3125 docs: fix the heading levels in some notebooks
  notebooks/tabular_examples/model_agnostic/Multioutput Regression SHAP.ipynb
  notebooks/tabular_examples/tree_based_models/Perfomance Comparison.ipynb
Labels: documentation, skip-changelog

#3104 DOCS: Add Sphinx release notes, remove manual Changelog
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/conf.py
  docs/index.rst
  docs/release_notes.rst
  pyproject.toml
Labels: documentation

#3128 MAINT: Fix path filter issue, move linter to seperate workflow
  .github/workflows/lint.yml
  .github/workflows/run_tests.yml
Labels: ci

#3134 MAINT: remove GitHub linter job for pre-commit.ci
  .github/workflows/lint.yml
Labels: ci

#3087 MAINT: Add wheels for musllinux arch
  pyproject.toml
Labels: ci

#3138 FIX: waterfall plot on explanations of sklearn tree models
  shap/plots/_waterfall.py
  tests/plots/test_waterfall.py
Labels: bug

#3157 ENH: Add heatmap and violin plot to main API
  shap/__init__.py
Labels: enhancement
