Repository shap/shap, pull requests merged in 2023-10, with the labels that each got.

#3214 Replaced Boston dataset with California in Catboost tutorial
  notebooks/tabular_examples/tree_based_models/Catboost tutorial.ipynb
Labels: documentation

#3253 DOCS: Remove redundant toctree level from API reference
  docs/conf.py
Labels: documentation

#3282 Refactor nb/census income xgboost
  .pre-commit-config.yaml
  notebooks/tabular_examples/tree_based_models/Census income classification with XGBoost.ipynb
Labels: documentation

#3234 DOCS: Lint tabular_examples/tree based models
  .pre-commit-config.yaml
  notebooks/tabular_examples/tree_based_models/Basic SHAP Interaction Value Example in XGBoost.ipynb
  notebooks/tabular_examples/tree_based_models/Catboost tutorial.ipynb
  notebooks/tabular_examples/tree_based_models/Census income classification with LightGBM.ipynb
  notebooks/tabular_examples/tree_based_models/Census income classification with XGBoost.ipynb
  notebooks/tabular_examples/tree_based_models/Example of loading a custom tree model into SHAP.ipynb
  notebooks/tabular_examples/tree_based_models/Explaining a simple OR function.ipynb
  notebooks/tabular_examples/tree_based_models/Explaining the Loss of a Model.ipynb
  notebooks/tabular_examples/tree_based_models/Fitting a Linear Simulation with XGBoost.ipynb
  notebooks/tabular_examples/tree_based_models/Force Plot Colors.ipynb
  notebooks/tabular_examples/tree_based_models/Front page example (XGBoost).ipynb
  notebooks/tabular_examples/tree_based_models/League of Legends Win Prediction with XGBoost.ipynb
  notebooks/tabular_examples/tree_based_models/NHANES I Survival Model.ipynb
  notebooks/tabular_examples/tree_based_models/Perfomance Comparison.ipynb
  notebooks/tabular_examples/tree_based_models/Python Version of Tree SHAP.ipynb
  notebooks/tabular_examples/tree_based_models/Scatter Density vs. Violin Plot Comparison.ipynb
  notebooks/tabular_examples/tree_based_models/Understanding Tree SHAP for Simple Models.ipynb
Labels: documentation

#3278 DOCS: Refactor nb/understanding tree shap
  .pre-commit-config.yaml
  notebooks/tabular_examples/tree_based_models/Understanding Tree SHAP for Simple Models.ipynb
Labels: documentation

#3235 DOCS: lint tabular examples/linear models
  .pre-commit-config.yaml
  notebooks/tabular_examples/linear_models/Explaining a model that uses standardized features.ipynb
  notebooks/tabular_examples/linear_models/Sentiment Analysis with Logistic Regression.ipynb
  notebooks/tabular_examples/model_agnostic/Census income classification with scikit-learn.ipynb
  notebooks/tabular_examples/model_agnostic/Diabetes regression.ipynb
  notebooks/tabular_examples/model_agnostic/Iris classification with scikit-learn.ipynb
  notebooks/tabular_examples/model_agnostic/Multioutput Regression SHAP.ipynb
  notebooks/tabular_examples/model_agnostic/Simple Boston Demo.ipynb
  notebooks/tabular_examples/model_agnostic/Simple Kernel SHAP.ipynb
  notebooks/tabular_examples/model_agnostic/Squashing Effect.ipynb
  notebooks/tabular_examples/neural_networks/Census income classification with Keras.ipynb
Labels: documentation

#3294 Fix/ngboost col sample lt 1
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug, enhancement

#3275 DOCS: clean up league of legends notebook
  notebooks/tabular_examples/tree_based_models/League of Legends Win Prediction with XGBoost.ipynb
Labels: documentation

#3304 update example of loading custom tree model into shap
  notebooks/tabular_examples/tree_based_models/Example of loading a custom tree model into SHAP.ipynb
Labels: documentation

#3303 DOCS: refactor census income classification notebook
  notebooks/tabular_examples/tree_based_models/Census income classification with LightGBM.ipynb
Labels: documentation

#3298 DOCS: Fix precommit regex statement, and lint remaining tabular examples
  .pre-commit-config.yaml
  notebooks/tabular_examples/model_agnostic/Simple Boston Demo.ipynb
  notebooks/tabular_examples/tree_based_models/Front page example (XGBoost).ipynb
  notebooks/tabular_examples/tree_based_models/Scatter Density vs. Violin Plot Comparison.ipynb
Labels: documentation, skip-changelog

#3306 Fix deprecated use of xgboost early_stopping_rounds
  shap/utils/_clustering.py
  tests/utils/test_clustering.py
Labels: bug

#3297 MAINT: Add release note template
  .github/release.yml
Labels: skip-changelog

#3315 refactor: raise error during init if masker is None for PermutationExplainer
  shap/explainers/_permutation.py
  tests/explainers/test_explainer.py
Labels: bug

#3316 refactor: remove boston dataset as promised
  docs/api.rst
  shap/datasets.py
Labels: BREAKING

#3296 MAINT: Bump version to 0.43.0
  shap/__init__.py
Labels: skip-changelog

#3301 DOCS: Lint notebooks/overviews
  .pre-commit-config.yaml
  notebooks/overviews/An introduction to explainable AI with Shapley values.ipynb
  notebooks/overviews/Be careful when interpreting predictive models in search of causal insights.ipynb
  notebooks/overviews/Explaining quantitative measures of fairness.ipynb
Labels: documentation, skip-changelog

#3325 Fix CatboostClassifier explanations with feature interactions on windows
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug

#3331 Cleanup disk before running CI tests on ubuntu
  .github/workflows/run_tests.yml
Labels: ci, skip-changelog

#3314 FIX: Xgboost sklearn model parameters that should be passed to xgboost.DMatrix
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug

#3312 CI: cancel only concurrent builds on PRs
  .github/workflows/run_tests.yml
Labels: ci, skip-changelog

#3332 Notebook simple boston demo
  notebooks/tabular_examples/model_agnostic/Simple Boston Demo.ipynb
  notebooks/tabular_examples/model_agnostic/Simple California Demo.ipynb
Labels: documentation

#3335 Notebook: Python Version of Tree SHAP
  notebooks/tabular_examples/tree_based_models/Python Version of Tree SHAP.ipynb
Labels: documentation

#3339 Notebook: benchmark xgboost
  notebooks/benchmarks/tabular/Benchmark XGBoost explanations.ipynb
Labels: documentation

#3322 MAINT: Simplify pre-commit hook specification
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#3336 Notebook: Force Plot Colors
  notebooks/tabular_examples/tree_based_models/Force Plot Colors.ipynb
Labels: documentation

#3337 Notebook: Front page example
  notebooks/tabular_examples/tree_based_models/Front page example (XGBoost).ipynb
Labels: documentation

#3074 chore: Add a Jupyter style guide and supporting infra
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/conf.py
Labels: documentation

#3271 ENH: replace np.linalg.inv and pinv by np.linalg.solve
  notebooks/tabular_examples/model_agnostic/Simple Kernel SHAP.ipynb
  shap/explainers/_kernel.py
Labels: enhancement

#3338 Notebook: Tabular prediction Benchmark
  notebooks/benchmarks/tabular/Tabular Prediction Benchmark Demo.ipynb
Labels: documentation

#3037 Revamp the "Explaining a simple OR function" notebook
  notebooks/tabular_examples/tree_based_models/Explaining a simple OR function.ipynb
Labels: documentation

#3341 Remove unnecessary `safe_isinstance` calls
  shap/benchmark/_explanation_error.py
  shap/benchmark/_sequential.py
  shap/benchmark/framework.py
  shap/benchmark/measures.py
  shap/explainers/_additive.py
  shap/explainers/_explainer.py
  shap/explainers/_kernel.py
  shap/explainers/_linear.py
  shap/explainers/_partition.py
  shap/explainers/_sampling.py
  shap/explainers/_tree.py
  shap/explainers/other/_lime.py
  shap/explainers/other/_maple.py
  shap/explainers/pytree.py
  shap/maskers/_tabular.py
  shap/plots/_bar.py
  shap/plots/_beeswarm.py
  shap/plots/_decision.py
  shap/plots/_force.py
  shap/plots/_monitoring.py
  shap/plots/_partial_dependence.py
  shap/plots/_scatter.py
  shap/plots/_violin.py
  shap/plots/_waterfall.py
  shap/utils/_clustering.py
  shap/utils/_general.py
  shap/utils/_legacy.py
Labels: skip-changelog

#3352 BUG: Explicitly specify constraint of xgboost>=1.4
  shap/explainers/_tree.py
Labels: bug, dependencies

#3359 fix: Convert DMatrix to CSR matrix if xgboost version allows
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug

#3346 update basic shap interaction xgboost notebook
  notebooks/tabular_examples/tree_based_models/Basic SHAP Interaction Value Example in XGBoost.ipynb
Labels: documentation

#3360 Default to "identity" instead of a callable in KernelExplainer
  shap/explainers/_kernel.py
Labels: skip-changelog

#3347 refactor census income classification
  notebooks/tabular_examples/tree_based_models/Census income classification with LightGBM.ipynb
Labels: documentation
