Repository shap/shap, pull requests merged in 2023-06, with the labels that each got.

#2950 Add GH Action for precommit hooks
  .github/workflows/run_tests.yml
Labels: ci

#2952 CI: Disable python test path filters
  .github/workflows/run_tests.yml
Labels: bug, ci

#2968 chore: re-enable ruff F811 and fix violations
  pyproject.toml
  shap/benchmark/experiments.py
  shap/utils/_general.py
Labels: ci

#2967 docs: fix some simple typos
  notebooks/overviews/An introduction to explainable AI with Shapley values.ipynb
  setup.py
  shap/_explanation.py
  shap/benchmark/methods.py
  shap/benchmark/plots.py
  shap/explainers/_additive.py
  shap/explainers/_deep/deep_tf.py
  shap/explainers/_exact.py
  shap/explainers/_explainer.py
  shap/explainers/_gradient.py
  shap/explainers/_kernel.py
  shap/explainers/_linear.py
  shap/explainers/_permutation.py
  shap/explainers/_sampling.py
  shap/explainers/_tree.py
  shap/explainers/other/_coefficent.py
  shap/explainers/other/_lime.py
  shap/explainers/other/_maple.py
Labels: documentation

#2981 Add GH Issue forms and Pull Request template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation

#2990 chore: update changelog entries
  CHANGELOG.md
Labels: documentation

#2996 Add contributing guidelines
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  CONTRIBUTING.md
Labels: documentation

#2995 Update wheel building
  .github/workflows/build_wheels.yml
  pyproject.toml
Labels: enhancement, ci

#3013 CI: Fix specification of python version in build_wheels.yml
  .github/workflows/build_wheels.yml
Labels: bug, ci

#3015 Wheel build - Skip tests for cp37 and cp38-macosx_x86_64
  .github/workflows/build_wheels.yml
  pyproject.toml
Labels: ci

#3022 Migrate static packaging metadata from setup.py to pyproject.toml, fix missing metadata
  pyproject.toml
  setup.py
Labels: bug, enhancement, dependencies

#3008 Move tokensizer to shared fixture
  tests/explainers/common.py
  tests/explainers/conftest.py
  tests/explainers/test_partition.py
Labels: bug, ci

#3003 refactor: Improve waterfall plot docs and checks using Explanation
  CHANGELOG.md
  shap/plots/_beeswarm.py
  shap/plots/_waterfall.py
  tests/plots/test_waterfall.py
Labels: documentation

#3017 FIX: Test against a full install, not an editable install
  .github/workflows/run_tests.yml
  CHANGELOG.md
  tests/__init__.py
Labels: bug, ci

#3029 Add Windows & Macos to CI test matrix
  .github/workflows/run_tests.yml
Labels: ci

#3039 docs: Missing datasets documentation
  docs/api.rst
  shap/datasets.py
Labels: documentation

#3028 FIX: Update cibuildwheel config with supported architectures and import-mode
  pyproject.toml
Labels: bug, ci

#3046 CHORE: Use faster test translation scenario, cut CI time by ~5mins
  pyproject.toml
  tests/explainers/conftest.py
Labels: enhancement, ci

#3044 FIX: Add fixture to set pyspark python driver
  CHANGELOG.md
  tests/explainers/test_tree.py
Labels: bug
