Repository shap/shap, pull requests merged in 2024-02, with the labels that each got.

#3485 MAINT: Increase operations limit of stale action
  .github/workflows/stale_issues.yml
Labels: skip-changelog

#3483 MAINT: Restore ngboost tests for py311
  pyproject.toml
Labels: dependencies, skip-changelog

#3414 Add support for python 3.12, drop support for 3.8
  .github/workflows/run_tests.yml
  pyproject.toml
  shap/explainers/_tree.py
Labels: enhancement, dependencies, BREAKING

#3490 MAINT: Update GH action versions
  .github/workflows/build_wheels.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/run_notebooks.yml
  .github/workflows/run_tests.yml
  .github/workflows/test_js.yml
Labels: ci, skip-changelog

#3488 MAINT: xfail on transformers connection errors
  tests/models/test_teacher_forcing_logits.py
Labels: skip-changelog

#3493 Add tests for XGB Random Forest models
  tests/explainers/test_tree.py
Labels: bug

#3497 define kernel to run notebooks
  scripts/run_notebooks_timeouts.py
Labels: ci, skip-changelog

#3501 MAINT: Include ngboost tests for python 3.12
  pyproject.toml
Labels: dependencies, skip-changelog

#3504 add selu activation for tensorflow deep explainer
  shap/explainers/_deep/deep_tf.py
  tests/explainers/test_deep.py
Labels: enhancement

#3506 ENH: Add support for special characters in catboost models
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: enhancement

#3458 Notebook: DeepExplainer Genomics Example
  notebooks/genomic_examples/DeepExplainer Genomics Example.ipynb
Labels: documentation

#3393 Notebook: Front Page DeepExplainer MNIST Example
  notebooks/image_examples/image_classification/Front Page DeepExplainer MNIST Example.ipynb
Labels: documentation

#3511 MAINT: Remove deprecated alias for Coefficient
  shap/explainers/other/__init__.py
Labels: BREAKING

#3512 MAINT: Update run_notebooks job to show tracebacks
  .github/workflows/run_notebooks.yml
  scripts/run_notebooks_timeouts.py
Labels: skip-changelog

#3462 Fixes for XGBoost model load and GPU build.
  setup.py
  shap/cext/gpu_treeshap.h
  shap/explainers/_gpu_tree.py
  shap/explainers/_tree.py
  tests/explainers/test_gpu_tree.py
  tests/explainers/test_tree.py
Labels: bug, enhancement

#3395 Refactor nb/nhanes survival model
  notebooks/tabular_examples/tree_based_models/NHANES I Survival Model.ipynb
  scripts/run_notebooks_timeouts.py
Labels: documentation

#3340 Remove deprecated option checks
  notebooks/tabular_examples/tree_based_models/Example of loading a custom tree model into SHAP.ipynb
  notebooks/tabular_examples/tree_based_models/Explaining the Loss of a Model.ipynb
  shap/benchmark/methods.py
  shap/explainers/_gpu_tree.py
  shap/explainers/_linear.py
  shap/explainers/_tree.py
  tests/explainers/test_explainer.py
  tests/explainers/test_linear.py
Labels: BREAKING

#3525 Restrict macos tests to test-core
  .github/workflows/run_tests.yml
Labels: bug, ci, skip-changelog

#3523 ENH: Prototype new plotting API for bar plot, accept and return axes
  notebooks/api_examples/plots/bar.ipynb
  scripts/run_notebooks_timeouts.py
  shap/plots/_bar.py
  tests/plots/baseline/test_simple_bar_local_feature_importance.png
  tests/plots/baseline/test_simple_bar_with_clustering.png
  tests/plots/test_bar.py
Labels: enhancement, BREAKING, visualization
