Repository shap/shap, pull requests merged in 2024-01, with the labels that each got.

#3435 Rearrange docs for PartitionExplainer
  shap/explainers/_partition.py
Labels: documentation

#3464 fix generated ids for html displaying
  shap/plots/_force.py
Labels: bug

#3345 Update XGBoost parsing to use ubjson format, replacing deprecated binary format
  shap/explainers/_tree.py
  shap/explainers/other/_ubjson.py
  tests/explainers/other/test_ubjson.py
  tests/explainers/test_tree.py
Labels: enhancement

#3460 add script to run notebooks in CI
  .github/workflows/run_notebooks.yml
  notebooks/overviews/Be careful when interpreting predictive models in search of causal insights.ipynb
  pyproject.toml
  scripts/run_notebooks_timeouts.py
  tests/explainers/test_tree.py
Labels: ci

#3459 Fix catboost regression error for shap interaction values
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug
