Repository shap/shap, pull requests merged in 2024-09, with the labels that each got.

#3838 fix: OpChain repr for kwargs-only operations
  shap/utils/_general.py
  tests/utils/test_general.py
Labels: bug

#3843 Fix failing CI on python 3.12 due to outdated numba & llvmlite
  pyproject.toml
Labels: dependencies, ci, skip-changelog

#3846 Error in documentation of shap.datasets.communitiesandcrime
  shap/datasets.py
Labels: bug, documentation

#3834 FIX: Improve handling of the `approximate` parameter to TreeExplainer for consistency, and deprecate the argument in the explainer's init method
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug

#3837 refactor: Cleanup explanation ops
  shap/_explanation.py
Labels: skip-changelog

#2624 MAINT refactor feature_perturbation in Tree explainers
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: todo, enhancement

#3853 docs: Use uv in readthedocs, RtD AddOn migration
  .readthedocs.yml
Labels: documentation

#3851 docs: use intersphinx for some external links
  docs/conf.py
  notebooks/image_examples/image_classification/Explain ResNet50 using the Partition explainer.ipynb
  notebooks/image_examples/image_classification/Image Multi Class.ipynb
  shap/datasets.py
  shap/explainers/_deep/__init__.py
  shap/explainers/_partition.py
  shap/plots/_bar.py
  shap/plots/_beeswarm.py
  shap/plots/_decision.py
  shap/plots/_force.py
  shap/plots/_heatmap.py
  shap/plots/_image.py
  shap/plots/_scatter.py
  shap/plots/_violin.py
  shap/plots/_waterfall.py
  shap/utils/_clustering.py
  tests/explainers/test_tree.py
Labels: documentation

#3856 MAINT: Remove deprecated unused code `_build_delta_masked_inputs` and `Explainer._compute_main_effects`
  shap/explainers/_explainer.py
  shap/plots/_text.py
  shap/utils/_masked_model.py
  tests/explainers/test_tree.py
Labels: bug

#3858 MAINT: Change default KernelExplainer l1reg to `numfeatures(10)`
  shap/explainers/_kernel.py
Labels: skip-changelog

#3849 ENH: Allow custom styles for bar plot
  shap/plots/_bar.py
  shap/plots/_heatmap.py
Labels: enhancement, visualization
