Repository shap/shap, pull requests merged in 2024-06, with the labels that each got.

#3713 MAINT: Bump test-core to use python 312
  .github/workflows/run_tests.yml
Labels: dependencies, skip-changelog

#3712 ENH: Add support for numpy 2, and test against numpy 1.X and 2.X
  .github/workflows/run_tests.yml
  pyproject.toml
  shap/cext/_cext.cc
  shap/cext/_cext_gpu.cc
Labels: enhancement, dependencies, ci

#3717 Remove deprecated parameter auto_size_plot
  shap/plots/_beeswarm.py
  shap/plots/_violin.py
Labels: BREAKING

#3718 MAINT: Bump GH action versions
  .github/workflows/build_wheels.yml
  .github/workflows/run_tests.yml
Labels: ci, skip-changelog

#3721 Add pre commit hook to check notebook order
  .pre-commit-config.yaml
Labels: documentation, skip-changelog

#3720 test decision plot
  shap/plots/_decision.py
  tests/plots/baseline/test_decision_plot.png
  tests/plots/baseline/test_decision_plot_interactions.png
  tests/plots/baseline/test_decision_plot_single_instance.png
  tests/plots/baseline/test_multioutput_decision.png
  tests/plots/test_decision.py
Labels: visualization

#3724 MAINT: Update git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: skip-changelog
