Repository shap/shap, pull requests merged in 2024-08, with the labels that each got.

#3771 CI: remove the disk-space job
  .github/workflows/run_tests.yml
Labels: ci, skip-changelog

#3775 MAINT: fixup string literal concatenation
  pyproject.toml
  shap/_serializable.py
  shap/explainers/_gpu_tree.py
  shap/explainers/_tree.py
  shap/maskers/_image.py
  shap/plots/_image.py
  shap/plots/_scatter.py
  shap/plots/_text.py
  shap/plots/_violin.py
  shap/utils/transformers.py
  tests/plots/test_bar.py
  tests/plots/test_beeswarm.py
  tests/plots/test_violin.py
Labels: skip-changelog

#3754 MAINT: Enable type checking for subset of shap.plots, update to PEP604
  pyproject.toml
  shap/_explanation.py
  shap/actions/_optimizer.py
  shap/explainers/_deep/__init__.py
  shap/explainers/_tree.py
  shap/models/_teacher_forcing.py
  shap/models/_text_generation.py
  shap/plots/_beeswarm.py
  shap/plots/_decision.py
  shap/plots/_embedding.py
  shap/plots/_group_difference.py
  shap/plots/_image.py
  shap/plots/_monitoring.py
  shap/plots/_partial_dependence.py
  shap/plots/_utils.py
  shap/plots/_violin.py
  shap/plots/colors/_colorconv.py
  shap/utils/_clustering.py
  shap/utils/_general.py
  shap/utils/_types.py
Labels: skip-changelog

#3786 Add tests for shap colors and colormaps
  shap/plots/colors/_colors.py
  tests/plots/baseline/test_colormaps_red_blue.png
  tests/plots/baseline/test_colormaps_red_blue_circle.png
  tests/plots/baseline/test_colormaps_red_blue_no_bounds.png
  tests/plots/baseline/test_colormaps_red_blue_transparent.png
  tests/plots/baseline/test_colormaps_red_transparent_blue.png
  tests/plots/baseline/test_colormaps_red_white_blue.png
  tests/plots/baseline/test_colormaps_transparent_blue.png
  tests/plots/baseline/test_colormaps_transparent_red.png
  tests/plots/test_colors.py
Labels: skip-changelog, visualization

#3785 FIX: Re-vendor colorconv from skimage 0.24.0
  pyproject.toml
  shap/plots/colors/_colorconv.py
Labels: visualization

#3787 MAINT: Switch run_notebooks.yml to use uv
  .github/workflows/run_notebooks.yml
Labels: ci, skip-changelog

#3790 MAINT: Add timeout to run_tests
  .github/workflows/run_tests.yml
Labels: ci, skip-changelog

#3789 MAINT: Tidy up baseline image names
  tests/plots/baseline/test_bar.png
  tests/plots/baseline/test_bar_local_feature_importance.png
  tests/plots/baseline/test_bar_with_clustering.png
  tests/plots/baseline/test_bar_with_cohorts_dict.png
  tests/plots/baseline/test_beeswarm.png
  tests/plots/baseline/test_decision_multioutput.png
  tests/plots/baseline/test_force_plot_negative_sign.png
  tests/plots/baseline/test_force_plot_positive_sign.png
  tests/plots/baseline/test_summary.png
  tests/plots/baseline/test_summary_bar_with_data.png
  tests/plots/baseline/test_summary_dot_with_data.png
  tests/plots/baseline/test_summary_layered_violin_with_data.png
  tests/plots/baseline/test_summary_multi_class.png
  tests/plots/baseline/test_summary_multi_class_legend.png
  tests/plots/baseline/test_summary_multi_class_legend_decimals.png
  tests/plots/baseline/test_summary_violin_with_data.png
  tests/plots/baseline/test_summary_with_data.png
  tests/plots/baseline/test_summary_with_log_scale.png
  tests/plots/test_bar.py
  tests/plots/test_beeswarm.py
  tests/plots/test_decision.py
  tests/plots/test_force.py
  tests/plots/test_summary.py
  tests/plots/test_violin.py
Labels: skip-changelog, visualization

#3792 MAINT: Improved isolation and cleanup of matplotlib tests
  tests/conftest.py
  tests/explainers/__init__.py
  tests/plots/conftest.py
  tests/plots/test_beeswarm.py
  tests/plots/test_decision.py
  tests/plots/test_dependence.py
  tests/plots/test_dependence_string_features.py
  tests/plots/test_force.py
  tests/plots/test_image.py
  tests/plots/test_summary.py
  tests/plots/test_violin.py
  tests/plots/test_waterfall.py
Labels: skip-changelog, visualization

#3791 MAINT: Add tests for scatter plot
  shap/plots/_scatter.py
  tests/plots/baseline/test_scatter_custom.png
  tests/plots/baseline/test_scatter_dotchain.png
  tests/plots/baseline/test_scatter_interaction.png
  tests/plots/baseline/test_scatter_multiple_cols_overlay.png
  tests/plots/baseline/test_scatter_single.png
  tests/plots/test_dependence.py
  tests/plots/test_scatter.py
  tests/plots/test_summary.py
Labels: skip-changelog, visualization

#3818 MAINT: Add numba lower version bound
  pyproject.toml
Labels: bug, ci, skip-changelog

#3706 #3135: Adds categorical support for shap.plots.scatter
  shap/plots/_scatter.py
  tests/plots/baseline/test_scatter_categorical.png
  tests/plots/test_scatter.py
Labels: enhancement, visualization

#3636 Fix label option for multiple rows in shap.plots.image
  shap/plots/_image.py
  tests/plots/baseline/test_image_multi.png
  tests/plots/baseline/test_image_single.png
  tests/plots/test_image.py
Labels: bug, visualization

#2848 ENH: introduce vmax parameter in image plot
  shap/plots/_image.py
Labels: enhancement, visualization

#3561 ENH: New plotting API for beeswarm so can accept and return Axes
  shap/plots/_beeswarm.py
Labels: enhancement, visualization

#3578 Fix transformers
  pyproject.toml
  shap/models/_topk_lm.py
  shap/utils/transformers.py
Labels: bug

#2225 Enabeling to create a beeswarm figure without sum of other features.
  shap/plots/_beeswarm.py
  tests/plots/baseline/test_beeswarm_no_group_remaining.png
  tests/plots/test_beeswarm.py
Labels: todo, enhancement, visualization

#3821 MAINT: Bump codeql action
  .github/workflows/codeql-analysis.yml
Labels: ci, skip-changelog

#3812 MAINT: Enable mypy on further modules
  pyproject.toml
  shap/explainers/_deep/__init__.py
  shap/explainers/other/_ubjson.py
  shap/maskers/_fixed_composite.py
  shap/plots/_beeswarm.py
  shap/plots/_heatmap.py
  tests/plots/test_beeswarm.py
Labels: skip-changelog

#3822 MAINT: Fixup unused variables from flake8-bugbear
  notebooks/genomic_examples/DeepExplainer Genomics Example.ipynb
  notebooks/text_examples/sentiment_analysis/Keras LSTM for IMDB Sentiment Classification.ipynb
  shap/explainers/_deep/deep_pytorch.py
  shap/explainers/_explainer.py
  shap/explainers/_gradient.py
  shap/explainers/_kernel.py
  shap/plots/_bar.py
  shap/plots/_beeswarm.py
  shap/plots/_force_matplotlib.py
  shap/plots/_group_difference.py
  shap/plots/_violin.py
  shap/utils/_show_progress.py
  tests/maskers/test_text.py
Labels: skip-changelog

#3811 ENH: Improved typing and docs for scatter plot
  .gitignore
  pyproject.toml
  shap/plots/_scatter.py
  tests/plots/test_scatter.py
Labels: documentation, visualization

#3815 chore: Add type hints for datasets module and improve docs
  shap/datasets.py
Labels: documentation, skip-changelog

#3788 ENH: New interface to customise visualisations
  pyproject.toml
  shap/plots/_style.py
  shap/plots/_waterfall.py
  shap/utils/_exceptions.py
  tests/plots/baseline/test_waterfall_bounds.png
  tests/plots/baseline/test_waterfall_custom_style.png
  tests/plots/conftest.py
  tests/plots/test_style.py
  tests/plots/test_waterfall.py
Labels: enhancement, visualization

#3833 refactor: plot utils and colors
  shap/plots/_scatter.py
  shap/plots/_utils.py
  shap/plots/colors/__init__.py
  shap/plots/colors/_colors.py
Labels: visualization
