Repository shap/shap, pull requests merged in 2024-07, with the labels that each got.

#3715 Add basic type hints
  .github/workflows/run_tests.yml
  pyproject.toml
  shap/__init__.py
  shap/explainers/_deep/__init__.py
  shap/explainers/_deep/deep_pytorch.py
  shap/explainers/_deep/deep_tf.py
  shap/explainers/_gpu_tree.py
  shap/explainers/_tree.py
  shap/plots/_decision.py
  shap/plots/_image.py
  shap/plots/colors/_colorconv.py
  shap/utils/_general.py
Labels: skip-changelog

#3728 MAINT: Incrementally update mypy config
  pyproject.toml
  shap/plots/_image.py
Labels: skip-changelog

#3729 MAINT: enable mypy on tests
  .github/workflows/run_tests.yml
  pyproject.toml
  shap/plots/colors/_colorconv.py
  tests/explainers/other/test_ubjson.py
  tests/explainers/test_deep.py
  tests/plots/test_dependence_string_features.py
Labels: skip-changelog

#3732 Enable type checking for _explaination.py
  pyproject.toml
  shap/_explanation.py
Labels: skip-changelog

#3733 Enable type checking for shap/actions
  pyproject.toml
  shap/actions/_action.py
  shap/actions/_optimizer.py
  tests/actions/_optimizer.py
Labels: skip-changelog

#3740 Fix mypy failure: set plt.subplots squeeze=False in _image.py
  shap/plots/_image.py
Labels: bug, skip-changelog

#3738 Fix TypeError in summary_plot
  shap/plots/_beeswarm.py
  tests/plots/test_summary.py
Labels: bug, visualization

#3739 Deprecate the legacy bar plot, add migration guide to new Explainer API
  docs/api_examples.rst
  notebooks/api_examples/migrating-to-new-api.ipynb
  shap/plots/_bar.py
Labels: BREAKING, visualization

#3746 MAINT: Remove redundant test fixture
  tests/explainers/conftest.py
Labels: skip-changelog

#3741 MAINT: Include ipywidgets in dev dependencies
  pyproject.toml
Labels: documentation, skip-changelog

#3749 DOCS: Fix column indices in Understanding Tree SHAP notebook
  notebooks/tabular_examples/tree_based_models/Understanding Tree SHAP for Simple Models.ipynb
Labels: documentation

#3734 Enable type checking for shap/utils, and improve OpChain docs
  pyproject.toml
  shap/_explanation.py
  shap/utils/_clustering.py
  shap/utils/_general.py
  shap/utils/_legacy.py
  shap/utils/_masked_model.py
  shap/utils/_types.py
Labels: skip-changelog

#3760 chore: Remove unnecessary double quotes after formatting
  shap/__init__.py
  shap/benchmark/_explanation_error.py
  shap/explainers/_tree.py
  shap/plots/_bar.py
  shap/plots/_beeswarm.py
  shap/plots/_decision.py
  shap/plots/_force.py
  shap/plots/_image.py
  shap/plots/_text.py
  shap/plots/_violin.py
  shap/plots/_waterfall.py
  shap/plots/colors/_colorconv.py
Labels: skip-changelog

#3761 refactor: Slight logic and docs cleanup of the clustering functions
  shap/utils/_clustering.py
  tests/utils/test_clustering.py
Labels: skip-changelog

#3755 DOCS: Remove unused "bar" notebook
  .pre-commit-config.yaml
  docs/notebooks/plots/bar.ipynb
Labels: documentation, skip-changelog

#3753 MAINT: Enable type checking for shap.models
  pyproject.toml
  shap/models/_model.py
  shap/models/_teacher_forcing.py
  shap/models/_text_generation.py
  shap/models/_topk_lm.py
Labels: skip-changelog

#3768 CI: Switch from pip to uv (~5min speedup), fix tensorflow/numpy constraint
  .github/workflows/run_tests.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies, ci, skip-changelog
