Repository shap/shap, pull requests merged in 2024-03, with the labels that each got.

#3531 Fix broken link and update plot description
  README.md
  notebooks/image_examples/image_classification/Front Page DeepExplainer MNIST Example.ipynb
Labels: documentation

#3530 Expose arg `s` for marker size in `beeswarm`
  shap/plots/_beeswarm.py
Labels: enhancement, visualization

#3518 fix macos segmentation fault
  .github/workflows/run_tests.yml
  pyproject.toml
Labels: bug, ci

#3533 ENH: 2x import time speedup via lazy importing of pytorch
  shap/explainers/_deep/deep_pytorch.py
  shap/explainers/_gradient.py
  shap/maskers/_image.py
  shap/models/_model.py
Labels: enhancement, dependencies

#3527 ENH: Specify default clustering as "cosine" if y is None
  shap/utils/_clustering.py
  tests/utils/test_clustering.py
Labels: enhancement

#3536 Fix text masking with certain tokenizers
  shap/maskers/_text.py
  tests/maskers/test_text.py
Labels: bug

#3540 Bump cibuildwheel to 2.16.5
  .github/workflows/build_wheels.yml
Labels: bug, ci, skip-changelog

#3541 Remove deprecation warning for permutation explainer
  shap/explainers/_permutation.py
Labels: skip-changelog

#3318 BREAKING: make shap explanations consistent for xgboost and lightgbm
  notebooks/tabular_examples/model_agnostic/Iris classification with scikit-learn.ipynb
  notebooks/tabular_examples/tree_based_models/Census income classification with LightGBM.ipynb
  shap/explainers/_deep/__init__.py
  shap/explainers/_deep/deep_pytorch.py
  shap/explainers/_deep/deep_tf.py
  shap/explainers/_gradient.py
  shap/explainers/_kernel.py
  shap/explainers/_linear.py
  shap/explainers/_tree.py
  shap/plots/_force.py
  tests/explainers/test_deep.py
  tests/explainers/test_gradient.py
  tests/explainers/test_kernel.py
  tests/explainers/test_linear.py
  tests/explainers/test_tree.py
  tests/plots/test_force.py
Labels: BREAKING

#3542 Fix issue with KernelExplainer when explaining tensorflow models
  shap/explainers/_kernel.py
  tests/explainers/test_kernel.py
Labels: bug

#3552 MAINT: Bump ruff version, fix updated rule UP032 (f-strings)
  .pre-commit-config.yaml
  notebooks/image_examples/image_classification/PyTorch Deep Explainer MNIST example.ipynb
  shap/benchmark/experiments.py
  shap/explainers/_kernel.py
  shap/explainers/_tree.py
  shap/plots/_decision.py
  shap/plots/_force.py
  tests/explainers/test_deep.py
Labels: skip-changelog

#3547 Fix force_plot contribution threshold for negative contributions
  shap/plots/_force_matplotlib.py
Labels: bug, visualization

#3556 reintroduce tests that were accidentally commented out
  tests/explainers/test_deep.py
Labels: skip-changelog

#3549 DOCS: Formatting and phrasing updates for SHAP return values
  shap/explainers/_deep/__init__.py
  shap/explainers/_gradient.py
  shap/explainers/_kernel.py
  shap/explainers/_linear.py
  shap/explainers/_tree.py
  shap/maskers/_image.py
Labels: documentation

#3558 Fix call interface for the deep explainer
  shap/explainers/_deep/__init__.py
  tests/explainers/test_deep.py
Labels: bug

#3563 MAINT: Pin tensorflow to <2.16
  pyproject.toml
Labels: dependencies, skip-changelog

#3543 Enhance dataset functions by adding docstrings and removing unused `d…
  shap/datasets.py
Labels: documentation, BREAKING

#3564 Include catboost tests for py312
  pyproject.toml
Labels: dependencies, ci, skip-changelog

#3566 Minor datasets docs fixups
  shap/datasets.py
Labels: documentation
