Repository shap/shap, pull requests merged in 2024-04, with the labels that each got.

#3567 MAINT: Minor simplifications and removal of duplication
  shap/_explanation.py
  shap/explainers/_kernel.py
  shap/explainers/_sampling.py
  shap/explainers/_tree.py
  shap/plots/_benchmark.py
  shap/utils/_masked_model.py
Labels: skip-changelog

#3571 ENH: Add ax option to heatmap plotting function
  shap/plots/_heatmap.py
Labels: enhancement, visualization

#3560 Update slicer pin to 0.0.8 and add test
  pyproject.toml
  tests/explainers/test_deep.py
Labels: dependencies, skip-changelog

#3620 seperate mistralai tests and let them xfail
  tests/maskers/test_text.py
Labels: ci

#3604 MAINT: Address pyod isolation forest test warning
  tests/explainers/test_tree.py
Labels: ci

#3627 FIX: Correct Data Type in Docstring for max_display in Waterfall Plot
  shap/plots/_waterfall.py
Labels: documentation

#3616 Fix missing `base_score` in xgboost regression
  shap/explainers/_tree.py
  tests/explainers/test_tree.py
Labels: bug

#3617 add selu activation for pytorch deep explainer
  shap/explainers/_deep/deep_pytorch.py
  tests/explainers/test_deep.py
Labels: enhancement
