Repository shap/shap, pull requests merged in 2025-01, with the labels that each got.

#3953 Fix: explicitly set matplotlib interpolation rcParams in tests
  shap/plots/_beeswarm.py
  tests/plots/test_image.py
  tests/plots/test_waterfall.py
Labels: dependencies, ci

#3955 MAINT: Skip sentiment analysis test on MacOS runners
  tests/explainers/test_deep.py
Labels: bug, ci

#3928 MAINT: simpler numpy pin for py3.12
  .github/workflows/run_tests.yml
  pyproject.toml
Labels: dependencies, skip-changelog

#3962 Fix typo in force plot with LightGBM and description
  notebooks/tabular_examples/tree_based_models/Census income classification with LightGBM.ipynb
Labels: documentation

#3957 Fix: fixed markdown issue with some sections title in the introductio…
  notebooks/overviews/An introduction to explainable AI with Shapley values.ipynb
Labels: documentation

#3960 Fix comment for beeswarm plot in intro notebook
  notebooks/overviews/An introduction to explainable AI with Shapley values.ipynb
Labels: documentation

#3927 MAINT: Fix Ruff UP031, bump ruff
  .pre-commit-config.yaml
  shap/benchmark/_sequential.py
  shap/benchmark/experiments.py
  shap/benchmark/plots.py
  shap/explainers/_deep/deep_tf.py
  shap/explainers/_tree.py
  shap/plots/_bar.py
  shap/plots/_beeswarm.py
  shap/plots/_group_difference.py
  shap/plots/_partial_dependence.py
  shap/plots/_violin.py
  shap/plots/_waterfall.py
Labels: skip-changelog

#3977 MAINT: Enable verbose upload to test pypi
  .github/workflows/build_wheels.yml
Labels: skip-changelog

#3976 MAINT: Disable conflicting lint rules
  pyproject.toml
Labels: skip-changelog

#3978 MAINT: Enable trusted publishing
  .github/workflows/build_wheels.yml
Labels: ci, skip-changelog
