Repository shap/shap, pull requests merged in 2025-03, with the labels that each got.

#4019 Fix huggingface issue
  tests/explainers/conftest.py
Labels: skip-changelog

#4039 update transformers version for macos, link github issue
  pyproject.toml
Labels: ci

#3273 Add experimental causalml support
  pyproject.toml
  shap/explainers/_tree.py
  shap/utils/_warnings.py
  tests/explainers/conftest.py
  tests/explainers/test_tree.py
Labels: enhancement

#4041 Fix/single unique value jitter
  shap/plots/_scatter.py
  tests/plots/baseline/test_scatter_plot_value_input_input0.png
  tests/plots/baseline/test_scatter_plot_value_input_input1.png
  tests/plots/baseline/test_scatter_plot_value_input_input2.png
  tests/plots/test_scatter.py
Labels: visualization
